preliminary implements of game event related logic
TISUnion/Carpet-TIS-Addition pull request #23
Opened 2021-03-22 06:42 UTC by Enzyme125

1.17更新了Sculk Sensor可能会对红石设计产生巨大的革新
初步实现了一个用来分析Sculk Sensor相关逻辑的logger
（还没有加翻译，UI还有点丑）
有什么想法可以再讨论下（？

**Preview**
![image](https://user-images.githubusercontent.com/36667224/111949793-4cdf9b80-8b1c-11eb-970d-aa878d9c08ca.png)

提供了`vibration` ,`all`, `sculk_sensed` 分别记录“振动”（可能会影响Sculk Sensor的），全部，已经激活Sculk Sensor的

2021-03-22 07:26 UTC, Fallen-Breath commented
给 game event 做一个记录器是好东西，不过我也担心 1.17 仍处于快照，game event 系统可能仍未定稿

不过既然你也说了仍待完善，我就先不把这个 PR 合并。能完善的地方也包括翻译，文档什么的

2021-03-22 07:28 UTC, Fallen-Breath commented
我曾有过将 game event 纳入 microTiming 记录器的打算，可惜 game event 源并非基于方块，与 microTiming 的框架不相容。将 game event 独立出来也是个好选择

2021-03-22 07:38 UTC, Enzyme125 commented
> 我曾有过将 game event 纳入 microTiming 记录器的打算，可惜 game event 源并非基于方块，与 microTiming 的框架不相容。将 game event 独立出来也是个好选择

对，我昨天开始写的时候也是想纳入microTiming，不过好多东西都要重新加，还不如重新开一个Logger了
感觉microTiming主要搞得还是setBlockState这样的

2021-03-22 07:41 UTC, Enzyme125 commented
> 给 game event 做一个记录器是好东西，不过我也担心 1.17 仍处于快照，game event 系统可能仍未定稿
> 
> 不过既然你也说了仍待完善，我就先不把这个 PR 合并。能完善的地方也包括翻译，文档什么的

UI之类的需要再改改吗？比如加个什么GameTime / World 之类的（有点像microTiming那种）

2021-03-22 10:26 UTC, Fallen-Breath commented
> UI之类的需要再改改吗？比如加个什么GameTime / World 之类的（有点像microTiming那种）

gametime 跟 world 我认为有必要显示，在调试精确时序时 gametime 会很有用

不过当显示的内容多起来后可能会导致显示的有些乱，这看你怎么排版了，可以试试将一些信息纳入悬浮文本中什么的

2021-03-22 10:34 UTC, Fallen-Breath commented on src/main/resources/assets/carpettisaddition/lang/zh_cn.json
> +  "logger.gameEvent.wow": "  哇塞！",
缩进用空格字符串不建议纳入翻译中，更适合直接硬编码

2021-03-22 10:36 UTC, Fallen-Breath commented on src/main/java/carpettisaddition/logging/loggers/gameevent/GameEventLogger.java
> +                            , Messenger.tp("c", pos), new ClickEvent(ClickEvent.Action.SUGGEST_COMMAND, TextUtil.getTeleportCommand(pos)))));
carpet 的 `Messenger` 的 `tp` 不支持跨维度 `tp`，可以试试 `TextUtil#getTeleportCommand`

2021-03-22 10:39 UTC, Fallen-Breath commented on src/main/java/carpettisaddition/logging/loggers/gameevent/GameEventLogger.java
> +                        , Messenger.tp("c", pos), new ClickEvent(ClickEvent.Action.SUGGEST_COMMAND, TextUtil.getTeleportCommand(pos)))
carpet 的 `Messenger` 的 `tp` 不支持维度显示，可以试试 `TextUtil#getCoordinateText`

2021-03-22 14:35 UTC, Enzyme125 commented
整体状态如图，左侧是事件ID，为了更好的甄别不同的事件在logger中分配的
![image](https://user-images.githubusercontent.com/36667224/112006077-58ec4d00-8b5e-11eb-8454-61377502c929.png)
鼠标放置在事件上，显示事件的特别属性
![image](https://user-images.githubusercontent.com/36667224/112006135-66a1d280-8b5e-11eb-90fe-ff012489bf67.png)
被潜声传感器检测到时，简要的显示初末位置，并给出提示（可以点击传送）
![image](https://user-images.githubusercontent.com/36667224/112006293-8f29cc80-8b5e-11eb-9db1-1106bea2fa35.png)
被羊毛阻止时
![image](https://user-images.githubusercontent.com/36667224/112006480-b6809980-8b5e-11eb-9d2e-6c8e8c9e5271.png)

2021-03-22 14:37 UTC, Enzyme125 commented on src/main/java/carpettisaddition/logging/loggers/gameevent/GameEventLogger.java
> +                        , Messenger.tp("c", pos), new ClickEvent(ClickEvent.Action.SUGGEST_COMMAND, TextUtil.getTeleportCommand(pos)))
已在https://github.com/TISUnion/Carpet-TIS-Addition/pull/23/commits/909cb5b9fea5c48697db022be4ee3ec3570c141f 中更改，鉴于开始已经打印了gametime和world，这里就不再重复打印了。

2021-03-22 14:38 UTC, Fallen-Breath commented on src/main/resources/assets/carpettisaddition/lang/zh_cn.json
> -
不同 logger 间的分隔符别去掉了

2021-03-22 14:39 UTC, Enzyme125 commented on src/main/resources/assets/carpettisaddition/lang/zh_cn.json
> -
c

2021-03-22 14:39 UTC, Fallen-Breath commented
我感觉不要滥用加粗字符，如果都为加粗的话不如不加粗

2021-03-22 14:41 UTC, Enzyme125 commented
> 我感觉不要滥用加粗字符，如果都为加粗的话不如不加粗

这个不就是开头的Label加了个粗（？

2021-03-22 14:42 UTC, Fallen-Breath commented
> > 我感觉不要滥用加粗字符，如果都为加粗的话不如不加粗
> 
> 这个不就是开头的Label加了个粗（？

事件 ID 及其后的彩色字符都加粗了，我并不认为这是值得突出的地方

2021-03-22 14:44 UTC, Enzyme125 commented
![image](https://user-images.githubusercontent.com/36667224/112008104-2b080800-8b60-11eb-8415-2a567b9eee9f.png)
这就改~（乖巧）

2021-03-22 14:48 UTC, Fallen-Breath commented on src/main/java/carpettisaddition/logging/loggers/gameevent/GameEventLogger.java
> +        if (this.gameEventContext.getProperties().getTime() != lastGameTick && registryKey == World.OVERWORLD)
其他维度发生的事件好像总不会进入这个 if 代码块中，因为 `registryKey == World.OVERWORLD` 总为假，导致 `addTickStartMessage` 并不会执行

2021-03-22 14:50 UTC, Fallen-Breath commented on src/main/java/carpettisaddition/logging/loggers/gameevent/GameEventLogger.java
> +                    getStyledPositionText("lb", pos, "$")));
此处为何要使用与其他位置标识符 `@` 不同的 `$`

2021-03-22 14:51 UTC, Enzyme125 commented on src/main/java/carpettisaddition/logging/loggers/gameevent/GameEventLogger.java
> +        if (this.gameEventContext.getProperties().getTime() != lastGameTick && registryKey == World.OVERWORLD)
确实如此，但这么写的原因是为了和microTiming统一，可能我的写法有点问题

2021-03-22 14:52 UTC, Enzyme125 commented on src/main/java/carpettisaddition/logging/loggers/gameevent/GameEventLogger.java
> +                    getStyledPositionText("lb", pos, "$")));
想说明这里是被Listener捕获的点

2021-03-22 14:53 UTC, Enzyme125 commented on src/main/java/carpettisaddition/logging/loggers/gameevent/GameEventLogger.java
> +                    getStyledPositionText("lb", pos, "$")));
下面那个用 @ 是因为看起来比较像“巨大的点”？

2021-03-22 14:53 UTC, Fallen-Breath commented on src/main/resources/assets/carpettisaddition/lang/zh_cn.json
> +  "logger.gameEvent.sculk_sensor": "潜声传感器",
对于这一类 mc 中已有翻译的文字，可直接使用 `TranslatableText`，而非手动再造一遍轮子。可参考 `carpettisaddition.utils.TextUtil#getBlockName`

2021-03-22 14:54 UTC, inclyc commented on src/main/java/carpettisaddition/logging/loggers/gameevent/GameEventLogger.java
> +                    getStyledPositionText("lb", pos, "$")));
因为实际上Sculk Sensor的范围比调用dispatchTo的范围小很多，所以这里强调这两个是不一样的
（一个是抽象的的Listener，一个是具象的Sculk Sensor）

2021-03-22 14:55 UTC, Enzyme125 commented on src/main/resources/assets/carpettisaddition/lang/zh_cn.json
> +  "logger.gameEvent.sculk_sensor": "潜声传感器",
行，感谢Fallen的建议

2021-03-22 14:55 UTC, Fallen-Breath commented on src/main/java/carpettisaddition/logging/loggers/gameevent/GameEventLogger.java
> +                    getStyledPositionText("lb", pos, "$")));
至少我看来，如无必要，含义相同的标识符只用一种标识符就行了。`@` 作为与单词 at 极为接近的一个字符我觉得用作位置标识符是挺好的

2021-03-22 14:57 UTC, Fallen-Breath commented on src/main/java/carpettisaddition/logging/loggers/gameevent/GameEventLogger.java
> +        if (this.gameEventContext.getProperties().getTime() != lastGameTick && registryKey == World.OVERWORLD)
不一定要保持和 microTiming 统一。microTiming 的思路是在一个 gt 中记录所有数据生成的树状图，并在 gt 结束时统一输出，这样可以防止输出被其他记录器打断，也可以便于对这棵完整的消息树进行后续处理，但同时也增加了不少复杂度

2021-03-22 14:58 UTC, Fallen-Breath commented on src/main/java/carpettisaddition/logging/loggers/gameevent/GameEventLogger.java
> +        if (this.gameEventContext.getProperties().getTime() != lastGameTick && registryKey == World.OVERWORLD)
我对 game event 不是非常了解，但如果 game event 不会出现复杂的递归调用的情况的话，即时输出我觉得是可以的，当然这就得考虑清楚 `addTickStartMessage` 该在什么时候执行

2021-03-25 07:25 UTC, Enzyme125 commented
![image](https://user-images.githubusercontent.com/36667224/112434117-2325af00-8d7e-11eb-91cb-1511a15be7de.png)
大改了下UI，重构代码。
现在计划整成可以打印屏蔽原因的

2021-04-09 06:09 UTC, Fallen-Breath commented
在自然世界中订阅该记录器会导致严重刷屏，得想办法消除这一点，比如没被捕获的游戏事件就不输出了？

2021-05-24 12:59 UTC, Fallen-Breath requested changes
需处理好 在自然世界中订阅该记录器会导致严重刷屏 这一点

2021-09-28 02:05 UTC, closed without merging